name: Master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: setup django settings
        run: |
          python manage.py makemigrations user core testsite
          python manage.py migrate
      - name: mypy
        run: |
          mypy config
          mypy user
          mypy core
          mypy testsite
#      - name: Test with pytest
#        run: |
#          pip install pytest
#          pytest
